/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#434655',
        'on-background': '#0b1c30',
        primary: '#004ac6',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#784b00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#996100',
        'on-tertiary-container': '#ffeedd',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        // Aliases for shadcn defaults (mapped to Unity & Growth tokens)
        foreground: '#0b1c30',
        muted: '#eff4ff',
        'muted-foreground': '#434655',
        accent: '#dce9ff',
        'accent-foreground': '#0b1c30',
        popover: '#ffffff',
        'popover-foreground': '#0b1c30',
        card: '#ffffff',
        'card-foreground': '#0b1c30',
        border: '#c3c6d7',
        input: '#c3c6d7',
        ring: '#004ac6',
        destructive: '#ba1a1a',
        'destructive-foreground': '#ffffff',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'container-padding': '24px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      boxShadow: {
        'card-1': '0px 4px 12px rgba(0, 0, 0, 0.05)',
        'card-2': '0px 12px 24px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
